### ISSUE TITLE
Unable to start the uber/stable-diffusion image

### ISSUE THREAD

**Issue by yhlf1990** [hyplabs/docker-stable-diffusion-webui#1]
There is an issue with starting the uber/stable-diffusion image.
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:3f263e1c5ffd0711f504a8dcc0eca225bbca1a9e9aa372dfcda2ecfd54f065e1                       0.0s
 => => naming to docker.io/uberi/stable-diffusion                                                                  0.0s
Warning: LDSR not found at path /home/dev/stable-diffusion-webui/repositories/latent-diffusion/LDSR.py
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
LatentDiffusion: Running in eps-prediction mode

**Comment by jjaquinta** [comment]
I, also, could not start, but for different reasons:
```
D:\Documents\ws\sd\docker>docker run --dns 0.0.0.0 --rm -t -p 7860:7860 uberi/stable-diffusion
Traceback (most recent call last):
  File "/home/dev/stable-diffusion-webui/webui.py", line 5, in <module>
    import modules.codeformer_model as codeformer
  File "/home/dev/stable-diffusion-webui/modules/codeformer_model.py", line 8, in <module>
    import modules.face_restoration
  File "/home/dev/stable-diffusion-webui/modules/face_restoration.py", line 1, in <module>
    from modules import shared
  File "/home/dev/stable-diffusion-webui/modules/shared.py", line 7, in <module>
    import gradio as gr
  File "/home/dev/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/dev/.local/lib/python3.10/site-packages/gradio/components.py", line 39, in <module>
    from gradio import media_data, processing_utils, utils
  File "/home/dev/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 17, in <module>
    from gradio import encryptor, utils
  File "/home/dev/.local/lib/python3.10/site-packages/gradio/utils.py", line 392, in <module>
    class Request:
  File "/home/dev/.local/lib/python3.10/site-packages/gradio/utils.py", line 412, in Request
    client = httpx.AsyncClient()
  File "/home/dev/.local/lib/python3.10/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/home/dev/.local/lib/python3.10/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/home/dev/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```
This happened both on Windows and Linux, so it's not a host problem.

**Comment by danielmaiahist** [comment]
> I, also, could not start, but for different reasons:
> 
> ```
> D:\Documents\ws\sd\docker>docker run --dns 0.0.0.0 --rm -t -p 7860:7860 uberi/stable-diffusion
> Traceback (most recent call last):
>   File "/home/dev/stable-diffusion-webui/webui.py", line 5, in <module>
>     import modules.codeformer_model as codeformer
>   File "/home/dev/stable-diffusion-webui/modules/codeformer_model.py", line 8, in <module>
>     import modules.face_restoration
>   File "/home/dev/stable-diffusion-webui/modules/face_restoration.py", line 1, in <module>
>     from modules import shared
>   File "/home/dev/stable-diffusion-webui/modules/shared.py", line 7, in <module>
>     import gradio as gr
>   File "/home/dev/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
>     import gradio.components as components
>   File "/home/dev/.local/lib/python3.10/site-packages/gradio/components.py", line 39, in <module>
>     from gradio import media_data, processing_utils, utils
>   File "/home/dev/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 17, in <module>
>     from gradio import encryptor, utils
>   File "/home/dev/.local/lib/python3.10/site-packages/gradio/utils.py", line 392, in <module>
>     class Request:
>   File "/home/dev/.local/lib/python3.10/site-packages/gradio/utils.py", line 412, in Request
>     client = httpx.AsyncClient()
>   File "/home/dev/.local/lib/python3.10/site-packages/httpx/_client.py", line 1397, in __init__
>     self._transport = self._init_transport(
>   File "/home/dev/.local/lib/python3.10/site-packages/httpx/_client.py", line 1445, in _init_transport
>     return AsyncHTTPTransport(
>   File "/home/dev/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 275, in __init__
>     self._pool = httpcore.AsyncConnectionPool(
> TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
> ```
> 
> This happened both on Windows and Linux, so it's not a host problem.

Same here.

**Comment by Adam-J-Roberts** [comment]
> dows and Linux, so it's not a host problem.

Three here
